### ISSUE TITLE
Ground truth images?

### ISSUE THREAD

**Issue by Jongulo** [VINHYU/CoSeR#4]
I've looked at the github, project page, and paper but you don't have any comparisons to the ground truth images you used for this. Could you please add them to at least one of these?

**Comment by VINHYU** [comment]
We have provided ground-truth images of all the comparisons we showed in the paper in a folder named "gt". However, it is important to note that the ground-truth images are only used as a reference for quality evaluation in real-world SR, and it is often the case that our SR results are clearer than the ground-truth images.
